---
title: Surplus production
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```

Simulate from a Schaefer surplus production model with both process and observation error:

```{r, fig.asp=1.2}
set.seed(1)
sim_schaefer <- function(K, r, q, sigma_pro, sigma_obs, N, C) {
  B <- numeric(N)
  U <- numeric(N)
  B[1] <- K
  U[1] <- q * B[1]
  for (i in 2:N) {
    B[i] <- B[i - 1] + r * B[i - 1] * (1 - (B[i - 1] / K)) - C[i - 1]
    B[i] <- B[i] * exp(rnorm(1, -(sigma_pro^2) / 2, sigma_pro)) # add process error
    if (B[i] <= 0) B[i] <- 0.01
    U[i] <- q * B[i]
  }
  index <- exp(log(U) + rnorm(N, -(sigma_obs^2) / 2, sigma_obs)) # add observation error
  list(index = index, catch = C, B = B)
}

catches <- c(seq(0, 80, length.out = 50), seq(80, 0, length.out = 50))
sim_dat <- sim_schaefer(K = 1000, r = 0.3, q = 0.1, sigma_pro = 0.1, sigma_obs = 0.2, 
  N = length(catches), C = catches)
par(mfrow = c(3, 1))
plot(sim_dat$index, type = "o")
plot(sim_dat$catch, type = "o")
plot(sim_dat$B, type = "o")
```

```{txt, code=readLines('schaefer_log.stan')}
```

```{r, stan-fit, warning=FALSE, message=FALSE}
library(cmdstanr)

catches <- sin(1.5 * pi * seq(-1, 1, length.out = 100)) * 30 + 40
plot(catches)
K <- 1000
r <- 0.25
q <- 0.1
sigma_pro <- 0.1
sigma_obs <- 0.1

set.seed(123)
sim_dat <- sim_schaefer(K = K, r = r, q = q, sigma_pro = sigma_pro, sigma_obs = sigma_obs,
  N = length(catches), C = catches)
par(mfrow = c(1, 1))
plot(sim_dat$index, type = "o")
par(mfrow = c(1, 1))
plot(sim_dat$catch, type = "o", ylab = "Catch", xlab = "Year")

dat <- list(
  C = sim_dat$catch,
  log_Uobs = log(sim_dat$index),
  init_depletion = 1,
  log_K_mean = log(K),
  log_q_mean = log(q),
  log_r_mean = log(r),
  log_K_sd = 2,
  log_q_sd = 1,
  log_r_sd = 1,
  N = length(sim_dat$catch)
)

init <- lapply(seq_len(4), function(i) {
  list(
    log_K = rnorm(1, log(K), 0.2),
    sigma_obs = rlnorm(1, log(sigma_pro), 0.05),
    sigma_pro = rlnorm(1, log(sigma_obs), 0.05),
    log_q = rnorm(1, log(q), 0.2), log_r = rnorm(1, log(r), 0.2),
    eps_raw = rep(0, length(catches))
  )
})

mod <- cmdstan_model("schaefer_ss_log.stan")
fit <- mod$sample(
  data = dat, init = init, parallel_chains = 4L,
  iter_sampling = 1000L, iter_warmup = 1000L, chains = 4L, seed = 123,
  adapt_delta = 0.9999, max_treedepth = 13L
)
fit$cmdstan_diagnose()
stanfit <- rstan::read_stan_csv(fit$output_files())
```

```{r}
print(stanfit, pars = c("log_K", "log_q", "log_r", "sigma_pro", "sigma_obs"))
pairs(stanfit, pars = c("log_K", "log_q", "log_r", "sigma_pro", "sigma_obs"))
p <- rstan::extract(stanfit)
par(mfrow = c(2, 3))
hist(exp(p$log_K));abline(v = K, col = "red", lwd = 1.5)
hist(exp(p$log_q));abline(v = q, col = "red", lwd = 1.5)
hist(exp(p$log_r));abline(v = r, col = "red", lwd = 1.5)
hist(p$sigma_obs);abline(v = sigma_obs, col = "red", lwd = 1.5)
hist(p$sigma_pro);abline(v = sigma_pro, col = "red", lwd = 1.5)
```
